version: "3.6"
services:
  web:
    image: 'gitlab/gitlab-ce:11.4.5-ce.0'
    ports:
      - '8080:80'
      - '8443:443'
      - '8022:22'
    volumes:
      - 'gitlab-config:/etc/gitlab'
      - 'gitlab-logs:/var/log/gitlab'
      - 'gitlab-data:/var/opt/gitlab'
volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data: