#Docker > 18.06.* + Compose 1.22
#
version: '3.7'

x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '6'

services:
  web:
    image: 'gitlab/gitlab-ce:11.7.0-ce.0'
    ports:
      - '8080:80'
      - '8443:443'
      - '8022:22'
    volumes:
      - 'gitlab-config:/etc/gitlab'
      - 'gitlab-logs:/var/log/gitlab'
      - 'gitlab-data:/var/opt/gitlab'
    restart: unless-stopped
    logging: *default-logging

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
